<?php

return [
  // 'client_id'     =>  env('ZOHOCRM_CLIENT_ID',''),
  // 'client_secret' =>  env('ZOHOCRM_CLIENT_SECRET',''),
  // 'grant_token' => env('ZOHOCRM_GRANT_TOKEN',''),
  // 'redirect_uri'  =>   env('ZOHOCRM_REDIRECT_URI',''),
  // 'accounts_url'  =>   env('ZOHOCRM_ACCOUNTS_URL',''),
  // 'access_type'   =>  env('ZOHOCRM_ACCESS_TYPE',''),
  // 'db_port'       =>  env('DB_PORT',3306),
  // 'token_persistence_path' => env('ZOHOCRM_TOKEN_PERSISTENCE_PATH',''),
  // 'persistence_handler_class' =>  env('ZOHOCRM_PERSISTENCE_HANDLER_CLASS',''),
  // 'client_email' => env('ZOHOCRM_CLIENT_EMAIL',''),
  // $configuration = [
    "accounts_url" => env('ZOHOCRM_ACCOUNTS_URL', NULL),
    "scope" => NULL,
    "state" => NULL,
    "OBTAIN_GRANT_TOKEN" => NULL,
    "response_type" => NULL,
    "code" => NULL,
    "client_id" => env('ZOHOCRM_CLIENT_ID',NULL),
    "client_secret" => env('ZOHOCRM_CLIENT_SECRET',NULL),
    "redirect_uri" => env('ZOHOCRM_REDIRECT_URI',NULL),
    "access_type" => env('ZOHOCRM_ACCESS_TYPE','offline'),
    "offline" => NULL,
    "online" => NULL,
    "prompt" => NULL,
    "consent" => NULL,
    "grant_type" => NULL,
    "authorization_code" => NULL,
    "code" => NULL,
    "grant_token" => NULL,
    "access_token" => NULL,
    "refresh_token" => NULL,
    "expires_in" => NULL,
    "expiry_time" => NULL,
    "persistence_handler_class" => env('ZOHOCRM_PERSISTENCE_HANDLER_CLASS', NULL),
    "token" => NULL,
    "dispatchTo" => NULL,
    "oauth_tokens" => NULL,
    "Zoho-oauthtoken",
    "Authorization" => NULL,
    "GET" => NULL,
    "POST" => NULL,
    "sandbox" => NULL,
    "token_persistence_path" => env('ZOHOCRM_TOKEN_PERSISTENCE_PATH', NULL),
    "db_port" => NULL,
    "db_username" => NULL,
    "db_password" => NULL,
    "200" => NULL,
];
