<?php

return [
    "accounts_url" => env('ZOHOCRM_ACCOUNTS_URL', NULL),
    "scope" => env('ZOHOCRM_SCOPE', NULL),
    "state" => env('ZOHOCRM_STATE', NULL),
    "OBTAIN_GRANT_TOKEN" => env('ZOHOCRM_OBTAIN_GRANT_TOKEN', NULL),
    "response_type" => env('ZOHOCRM_RESPONSE_TYPE', NULL),
    "code" => env('ZOHOCRM_CODE', NULL),
    "client_id" => env('ZOHOCRM_CLIENT_ID',NULL),
    "client_secret" => env('ZOHOCRM_CLIENT_SECRET',NULL),
    "redirect_uri" => env('ZOHOCRM_REDIRECT_URI',NULL),
    "access_type" => env('ZOHOCRM_ACCESS_TYPE','offline'),
    "offline" => env('ZOHOCRM_OFFLINE', NULL),
    "online" => env('ZOHOCRM_ONLINE', NULL),
    "prompt" => env('ZOHOCRM_PROMPT', NULL),
    "consent" => env('ZOHOCRM_CONSENT', NULL),
    "grant_type" => env('ZOHOCRM_GRANT_TYPE', NULL),
    "authorization_code" => env('ZOHOCRM_AUTHORIZATION_CODE', NULL),
    "code" => env('ZOHOCRM_CODE', NULL),
    "grant_token" => env('ZOHOCRM_GRANT_TOKEN', NULL),
    "access_token" => env('ZOHOCRM_ACCESS_TOKEN', NULL),
    "refresh_token" => env('ZOHOCRM_REFRESH_TOKEN', NULL),
    "expires_in" => env('ZOHOCRM_EXPIRES_IN', NULL),
    "expiry_time" => env('ZOHOCRM_EXPIRY_TIME', NULL),
    "persistence_handler_class" => env('ZOHOCRM_PERSISTENCE_HANDLER_CLASS', NULL),
    "token" => env('ZOHOCRM_TOKEN', NULL),
    "dispatchTo" => env('ZOHOCRM_DISPATCH_TO', NULL),
    "oauth_tokens" => env('ZOHOCRM_OAUTH_TOKENS', NULL),
    "Zoho-oauthtoken" => env('ZOHOCRM_OAUTH_ZOHO-OAUTHTOKEN', NULL),
    "Authorization" => env('ZOHOCRM_AUTHORIZATION', NULL),
    "GET" => env('ZOHOCRM_GET', NULL),
    "POST" => env('ZOHOCRM_POSR', NULL),
    "sandbox" => env('ZOHOCRM_SANDBOX', NULL),
    "token_persistence_path" => env('ZOHOCRM_TOKEN_PERSISTENCE_PATH', NULL),
    "db_port" => env('ZOHOCRM_DB_PORT', NULL),
    "db_username" => env('ZOHOCRM_DB_USERNAME', NULL),
    "db_password" => env('ZOHOCRM_DB_PASSWORD', NULL),
    "200" => env('ZOHOCRM_200', NULL)
];
